// Code generated by cssgen; DO NOT EDIT.
// Source: spec version mdn-latest at 2025-09-01T01:22:06+03:00

package cssgen

import "github.com/ahmed-com/typesafe-css/css"

// Type-safe setter functions for CSS properties.

// SetAccentColor creates a declaration for the accent-color property.
func SetAccentColor(v AccentColorVal) css.Decl {
	return css.Set(AccentColor, css.Keyword(string(v)))
}

// SetAlignContent creates a declaration for the align-content property.
func SetAlignContent(v AlignContentVal) css.Decl {
	return css.Set(AlignContent, css.Keyword(string(v)))
}

// SetAlignItems creates a declaration for the align-items property.
func SetAlignItems(v AlignItemsVal) css.Decl {
	return css.Set(AlignItems, css.Keyword(string(v)))
}

// SetAlignSelf creates a declaration for the align-self property.
func SetAlignSelf(v AlignSelfVal) css.Decl {
	return css.Set(AlignSelf, css.Keyword(string(v)))
}

// SetAlignTracks creates a declaration for the align-tracks property.
func SetAlignTracks(v AlignTracksVal) css.Decl {
	return css.Set(AlignTracks, css.Keyword(string(v)))
}

// SetAlignmentBaseline creates a declaration for the alignment-baseline property.
func SetAlignmentBaseline(v AlignmentBaselineVal) css.Decl {
	return css.Set(AlignmentBaseline, css.Keyword(string(v)))
}

// SetAll creates a declaration for the all property.
func SetAll(v AllVal) css.Decl {
	return css.Set(All, css.Keyword(string(v)))
}

// SetAnimation creates a declaration for the animation property.
func SetAnimation(v AnimationVal) css.Decl {
	return css.Set(Animation, css.Keyword(string(v)))
}

// SetAnimationComposition creates a declaration for the animation-composition property.
func SetAnimationComposition(v AnimationCompositionVal) css.Decl {
	return css.Set(AnimationComposition, css.Keyword(string(v)))
}

// SetAnimationDelay creates a declaration for the animation-delay property.
func SetAnimationDelay(v AnimationDelayVal) css.Decl {
	return css.Set(AnimationDelay, css.Keyword(string(v)))
}

// SetAnimationDirection creates a declaration for the animation-direction property.
func SetAnimationDirection(v AnimationDirectionVal) css.Decl {
	return css.Set(AnimationDirection, css.Keyword(string(v)))
}

// SetAnimationDuration creates a declaration for the animation-duration property.
func SetAnimationDuration(v AnimationDurationVal) css.Decl {
	return css.Set(AnimationDuration, css.Keyword(string(v)))
}

// SetAnimationFillMode creates a declaration for the animation-fill-mode property.
func SetAnimationFillMode(v AnimationFillModeVal) css.Decl {
	return css.Set(AnimationFillMode, css.Keyword(string(v)))
}

// SetAnimationIterationCount creates a declaration for the animation-iteration-count property.
func SetAnimationIterationCount(v AnimationIterationCountVal) css.Decl {
	return css.Set(AnimationIterationCount, css.Keyword(string(v)))
}

// SetAnimationName creates a declaration for the animation-name property.
func SetAnimationName(v AnimationNameVal) css.Decl {
	return css.Set(AnimationName, css.Keyword(string(v)))
}

// SetAnimationPlayState creates a declaration for the animation-play-state property.
func SetAnimationPlayState(v AnimationPlayStateVal) css.Decl {
	return css.Set(AnimationPlayState, css.Keyword(string(v)))
}

// SetAnimationTimingFunction creates a declaration for the animation-timing-function property.
func SetAnimationTimingFunction(v AnimationTimingFunctionVal) css.Decl {
	return css.Set(AnimationTimingFunction, css.Keyword(string(v)))
}

// SetAppearance creates a declaration for the appearance property.
func SetAppearance(v AppearanceVal) css.Decl {
	return css.Set(Appearance, css.Keyword(string(v)))
}

// SetAspectRatio creates a declaration for the aspect-ratio property.
func SetAspectRatio(v AspectRatioVal) css.Decl {
	return css.Set(AspectRatio, css.Keyword(string(v)))
}

// SetBackdropFilter creates a declaration for the backdrop-filter property.
func SetBackdropFilter(v BackdropFilterVal) css.Decl {
	return css.Set(BackdropFilter, css.Keyword(string(v)))
}

// SetBackfaceVisibility creates a declaration for the backface-visibility property.
func SetBackfaceVisibility(v BackfaceVisibilityVal) css.Decl {
	return css.Set(BackfaceVisibility, css.Keyword(string(v)))
}

// SetBackground creates a declaration for the background property.
func SetBackground(v BackgroundVal) css.Decl {
	return css.Set(Background, css.Keyword(string(v)))
}

// SetBackgroundAttachment creates a declaration for the background-attachment property.
func SetBackgroundAttachment(v BackgroundAttachmentVal) css.Decl {
	return css.Set(BackgroundAttachment, css.Keyword(string(v)))
}

// SetBackgroundBlendMode creates a declaration for the background-blend-mode property.
func SetBackgroundBlendMode(v BackgroundBlendModeVal) css.Decl {
	return css.Set(BackgroundBlendMode, css.Keyword(string(v)))
}

// SetBackgroundClip creates a declaration for the background-clip property.
func SetBackgroundClip(v BackgroundClipVal) css.Decl {
	return css.Set(BackgroundClip, css.Keyword(string(v)))
}

// SetBackgroundColor creates a declaration for the background-color property.
func SetBackgroundColor(v BackgroundColorVal) css.Decl {
	return css.Set(BackgroundColor, css.Keyword(string(v)))
}

// SetBackgroundImage creates a declaration for the background-image property.
func SetBackgroundImage(v BackgroundImageVal) css.Decl {
	return css.Set(BackgroundImage, css.Keyword(string(v)))
}

// SetBackgroundOrigin creates a declaration for the background-origin property.
func SetBackgroundOrigin(v BackgroundOriginVal) css.Decl {
	return css.Set(BackgroundOrigin, css.Keyword(string(v)))
}

// SetBackgroundPosition creates a declaration for the background-position property.
func SetBackgroundPosition(v BackgroundPositionVal) css.Decl {
	return css.Set(BackgroundPosition, css.Keyword(string(v)))
}

// SetBackgroundPositionX creates a declaration for the background-position-x property.
func SetBackgroundPositionX(v BackgroundPositionXVal) css.Decl {
	return css.Set(BackgroundPositionX, css.Keyword(string(v)))
}

// SetBackgroundPositionY creates a declaration for the background-position-y property.
func SetBackgroundPositionY(v BackgroundPositionYVal) css.Decl {
	return css.Set(BackgroundPositionY, css.Keyword(string(v)))
}

// SetBackgroundRepeat creates a declaration for the background-repeat property.
func SetBackgroundRepeat(v BackgroundRepeatVal) css.Decl {
	return css.Set(BackgroundRepeat, css.Keyword(string(v)))
}

// SetBackgroundSize creates a declaration for the background-size property.
func SetBackgroundSize(v BackgroundSizeVal) css.Decl {
	return css.Set(BackgroundSize, css.Keyword(string(v)))
}

// SetBaselineShift creates a declaration for the baseline-shift property.
func SetBaselineShift(v BaselineShiftVal) css.Decl {
	return css.Set(BaselineShift, css.Keyword(string(v)))
}

// SetBlockSize creates a declaration for the block-size property.
func SetBlockSize(v BlockSizeVal) css.Decl {
	return css.Set(BlockSize, css.Keyword(string(v)))
}

// SetBorder creates a declaration for the border property.
func SetBorder(v BorderVal) css.Decl {
	return css.Set(Border, css.Keyword(string(v)))
}

// SetBorderBlock creates a declaration for the border-block property.
func SetBorderBlock(v BorderBlockVal) css.Decl {
	return css.Set(BorderBlock, css.Keyword(string(v)))
}

// SetBorderBlockColor creates a declaration for the border-block-color property.
func SetBorderBlockColor(v BorderBlockColorVal) css.Decl {
	return css.Set(BorderBlockColor, css.Keyword(string(v)))
}

// SetBorderBlockEnd creates a declaration for the border-block-end property.
func SetBorderBlockEnd(v BorderBlockEndVal) css.Decl {
	return css.Set(BorderBlockEnd, css.Keyword(string(v)))
}

// SetBorderBlockEndColor creates a declaration for the border-block-end-color property.
func SetBorderBlockEndColor(v BorderBlockEndColorVal) css.Decl {
	return css.Set(BorderBlockEndColor, css.Keyword(string(v)))
}

// SetBorderBlockEndStyle creates a declaration for the border-block-end-style property.
func SetBorderBlockEndStyle(v BorderBlockEndStyleVal) css.Decl {
	return css.Set(BorderBlockEndStyle, css.Keyword(string(v)))
}

// SetBorderBlockEndWidth creates a declaration for the border-block-end-width property.
func SetBorderBlockEndWidth(v BorderBlockEndWidthVal) css.Decl {
	return css.Set(BorderBlockEndWidth, css.Keyword(string(v)))
}

// SetBorderBlockStart creates a declaration for the border-block-start property.
func SetBorderBlockStart(v BorderBlockStartVal) css.Decl {
	return css.Set(BorderBlockStart, css.Keyword(string(v)))
}

// SetBorderBlockStartColor creates a declaration for the border-block-start-color property.
func SetBorderBlockStartColor(v BorderBlockStartColorVal) css.Decl {
	return css.Set(BorderBlockStartColor, css.Keyword(string(v)))
}

// SetBorderBlockStartStyle creates a declaration for the border-block-start-style property.
func SetBorderBlockStartStyle(v BorderBlockStartStyleVal) css.Decl {
	return css.Set(BorderBlockStartStyle, css.Keyword(string(v)))
}

// SetBorderBlockStartWidth creates a declaration for the border-block-start-width property.
func SetBorderBlockStartWidth(v BorderBlockStartWidthVal) css.Decl {
	return css.Set(BorderBlockStartWidth, css.Keyword(string(v)))
}

// SetBorderBlockStyle creates a declaration for the border-block-style property.
func SetBorderBlockStyle(v BorderBlockStyleVal) css.Decl {
	return css.Set(BorderBlockStyle, css.Keyword(string(v)))
}

// SetBorderBlockWidth creates a declaration for the border-block-width property.
func SetBorderBlockWidth(v BorderBlockWidthVal) css.Decl {
	return css.Set(BorderBlockWidth, css.Keyword(string(v)))
}

// SetBorderBottom creates a declaration for the border-bottom property.
func SetBorderBottom(v BorderBottomVal) css.Decl {
	return css.Set(BorderBottom, css.Keyword(string(v)))
}

// SetBorderBottomColor creates a declaration for the border-bottom-color property.
func SetBorderBottomColor(v BorderBottomColorVal) css.Decl {
	return css.Set(BorderBottomColor, css.Keyword(string(v)))
}

// SetBorderBottomLeftRadius creates a declaration for the border-bottom-left-radius property.
func SetBorderBottomLeftRadius(v BorderBottomLeftRadiusVal) css.Decl {
	return css.Set(BorderBottomLeftRadius, css.Keyword(string(v)))
}

// SetBorderBottomRightRadius creates a declaration for the border-bottom-right-radius property.
func SetBorderBottomRightRadius(v BorderBottomRightRadiusVal) css.Decl {
	return css.Set(BorderBottomRightRadius, css.Keyword(string(v)))
}

// SetBorderBottomStyle creates a declaration for the border-bottom-style property.
func SetBorderBottomStyle(v BorderBottomStyleVal) css.Decl {
	return css.Set(BorderBottomStyle, css.Keyword(string(v)))
}

// SetBorderBottomWidth creates a declaration for the border-bottom-width property.
func SetBorderBottomWidth(v BorderBottomWidthVal) css.Decl {
	return css.Set(BorderBottomWidth, css.Keyword(string(v)))
}

// SetBorderCollapse creates a declaration for the border-collapse property.
func SetBorderCollapse(v BorderCollapseVal) css.Decl {
	return css.Set(BorderCollapse, css.Keyword(string(v)))
}

// SetBorderColor creates a declaration for the border-color property.
func SetBorderColor(v BorderColorVal) css.Decl {
	return css.Set(BorderColor, css.Keyword(string(v)))
}

// SetBorderEndEndRadius creates a declaration for the border-end-end-radius property.
func SetBorderEndEndRadius(v BorderEndEndRadiusVal) css.Decl {
	return css.Set(BorderEndEndRadius, css.Keyword(string(v)))
}

// SetBorderEndStartRadius creates a declaration for the border-end-start-radius property.
func SetBorderEndStartRadius(v BorderEndStartRadiusVal) css.Decl {
	return css.Set(BorderEndStartRadius, css.Keyword(string(v)))
}

// SetBorderImage creates a declaration for the border-image property.
func SetBorderImage(v BorderImageVal) css.Decl {
	return css.Set(BorderImage, css.Keyword(string(v)))
}

// SetBorderImageOutset creates a declaration for the border-image-outset property.
func SetBorderImageOutset(v BorderImageOutsetVal) css.Decl {
	return css.Set(BorderImageOutset, css.Keyword(string(v)))
}

// SetBorderImageRepeat creates a declaration for the border-image-repeat property.
func SetBorderImageRepeat(v BorderImageRepeatVal) css.Decl {
	return css.Set(BorderImageRepeat, css.Keyword(string(v)))
}

// SetBorderImageSlice creates a declaration for the border-image-slice property.
func SetBorderImageSlice(v BorderImageSliceVal) css.Decl {
	return css.Set(BorderImageSlice, css.Keyword(string(v)))
}

// SetBorderImageSource creates a declaration for the border-image-source property.
func SetBorderImageSource(v BorderImageSourceVal) css.Decl {
	return css.Set(BorderImageSource, css.Keyword(string(v)))
}

// SetBorderImageWidth creates a declaration for the border-image-width property.
func SetBorderImageWidth(v BorderImageWidthVal) css.Decl {
	return css.Set(BorderImageWidth, css.Keyword(string(v)))
}

// SetBorderInline creates a declaration for the border-inline property.
func SetBorderInline(v BorderInlineVal) css.Decl {
	return css.Set(BorderInline, css.Keyword(string(v)))
}

// SetBorderInlineColor creates a declaration for the border-inline-color property.
func SetBorderInlineColor(v BorderInlineColorVal) css.Decl {
	return css.Set(BorderInlineColor, css.Keyword(string(v)))
}

// SetBorderInlineEnd creates a declaration for the border-inline-end property.
func SetBorderInlineEnd(v BorderInlineEndVal) css.Decl {
	return css.Set(BorderInlineEnd, css.Keyword(string(v)))
}

// SetBorderInlineEndColor creates a declaration for the border-inline-end-color property.
func SetBorderInlineEndColor(v BorderInlineEndColorVal) css.Decl {
	return css.Set(BorderInlineEndColor, css.Keyword(string(v)))
}

// SetBorderInlineEndStyle creates a declaration for the border-inline-end-style property.
func SetBorderInlineEndStyle(v BorderInlineEndStyleVal) css.Decl {
	return css.Set(BorderInlineEndStyle, css.Keyword(string(v)))
}

// SetBorderInlineEndWidth creates a declaration for the border-inline-end-width property.
func SetBorderInlineEndWidth(v BorderInlineEndWidthVal) css.Decl {
	return css.Set(BorderInlineEndWidth, css.Keyword(string(v)))
}

// SetBorderInlineStart creates a declaration for the border-inline-start property.
func SetBorderInlineStart(v BorderInlineStartVal) css.Decl {
	return css.Set(BorderInlineStart, css.Keyword(string(v)))
}

// SetBorderInlineStartColor creates a declaration for the border-inline-start-color property.
func SetBorderInlineStartColor(v BorderInlineStartColorVal) css.Decl {
	return css.Set(BorderInlineStartColor, css.Keyword(string(v)))
}

// SetBorderInlineStartStyle creates a declaration for the border-inline-start-style property.
func SetBorderInlineStartStyle(v BorderInlineStartStyleVal) css.Decl {
	return css.Set(BorderInlineStartStyle, css.Keyword(string(v)))
}

// SetBorderInlineStartWidth creates a declaration for the border-inline-start-width property.
func SetBorderInlineStartWidth(v BorderInlineStartWidthVal) css.Decl {
	return css.Set(BorderInlineStartWidth, css.Keyword(string(v)))
}

// SetBorderInlineStyle creates a declaration for the border-inline-style property.
func SetBorderInlineStyle(v BorderInlineStyleVal) css.Decl {
	return css.Set(BorderInlineStyle, css.Keyword(string(v)))
}

// SetBorderInlineWidth creates a declaration for the border-inline-width property.
func SetBorderInlineWidth(v BorderInlineWidthVal) css.Decl {
	return css.Set(BorderInlineWidth, css.Keyword(string(v)))
}

// SetBorderLeft creates a declaration for the border-left property.
func SetBorderLeft(v BorderLeftVal) css.Decl {
	return css.Set(BorderLeft, css.Keyword(string(v)))
}

// SetBorderLeftColor creates a declaration for the border-left-color property.
func SetBorderLeftColor(v BorderLeftColorVal) css.Decl {
	return css.Set(BorderLeftColor, css.Keyword(string(v)))
}

// SetBorderLeftStyle creates a declaration for the border-left-style property.
func SetBorderLeftStyle(v BorderLeftStyleVal) css.Decl {
	return css.Set(BorderLeftStyle, css.Keyword(string(v)))
}

// SetBorderLeftWidth creates a declaration for the border-left-width property.
func SetBorderLeftWidth(v BorderLeftWidthVal) css.Decl {
	return css.Set(BorderLeftWidth, css.Keyword(string(v)))
}

// SetBorderRadius creates a declaration for the border-radius property.
func SetBorderRadius(v BorderRadiusVal) css.Decl {
	return css.Set(BorderRadius, css.Keyword(string(v)))
}

// SetBorderRight creates a declaration for the border-right property.
func SetBorderRight(v BorderRightVal) css.Decl {
	return css.Set(BorderRight, css.Keyword(string(v)))
}

// SetBorderRightColor creates a declaration for the border-right-color property.
func SetBorderRightColor(v BorderRightColorVal) css.Decl {
	return css.Set(BorderRightColor, css.Keyword(string(v)))
}

// SetBorderRightStyle creates a declaration for the border-right-style property.
func SetBorderRightStyle(v BorderRightStyleVal) css.Decl {
	return css.Set(BorderRightStyle, css.Keyword(string(v)))
}

// SetBorderRightWidth creates a declaration for the border-right-width property.
func SetBorderRightWidth(v BorderRightWidthVal) css.Decl {
	return css.Set(BorderRightWidth, css.Keyword(string(v)))
}

// SetBorderSpacing creates a declaration for the border-spacing property.
func SetBorderSpacing(v BorderSpacingVal) css.Decl {
	return css.Set(BorderSpacing, css.Keyword(string(v)))
}

// SetBorderStartEndRadius creates a declaration for the border-start-end-radius property.
func SetBorderStartEndRadius(v BorderStartEndRadiusVal) css.Decl {
	return css.Set(BorderStartEndRadius, css.Keyword(string(v)))
}

// SetBorderStartStartRadius creates a declaration for the border-start-start-radius property.
func SetBorderStartStartRadius(v BorderStartStartRadiusVal) css.Decl {
	return css.Set(BorderStartStartRadius, css.Keyword(string(v)))
}

// SetBorderStyle creates a declaration for the border-style property.
func SetBorderStyle(v BorderStyleVal) css.Decl {
	return css.Set(BorderStyle, css.Keyword(string(v)))
}

// SetBorderTop creates a declaration for the border-top property.
func SetBorderTop(v BorderTopVal) css.Decl {
	return css.Set(BorderTop, css.Keyword(string(v)))
}

// SetBorderTopColor creates a declaration for the border-top-color property.
func SetBorderTopColor(v BorderTopColorVal) css.Decl {
	return css.Set(BorderTopColor, css.Keyword(string(v)))
}

// SetBorderTopLeftRadius creates a declaration for the border-top-left-radius property.
func SetBorderTopLeftRadius(v BorderTopLeftRadiusVal) css.Decl {
	return css.Set(BorderTopLeftRadius, css.Keyword(string(v)))
}

// SetBorderTopRightRadius creates a declaration for the border-top-right-radius property.
func SetBorderTopRightRadius(v BorderTopRightRadiusVal) css.Decl {
	return css.Set(BorderTopRightRadius, css.Keyword(string(v)))
}

// SetBorderTopStyle creates a declaration for the border-top-style property.
func SetBorderTopStyle(v BorderTopStyleVal) css.Decl {
	return css.Set(BorderTopStyle, css.Keyword(string(v)))
}

// SetBorderTopWidth creates a declaration for the border-top-width property.
func SetBorderTopWidth(v BorderTopWidthVal) css.Decl {
	return css.Set(BorderTopWidth, css.Keyword(string(v)))
}

// SetBorderWidth creates a declaration for the border-width property.
func SetBorderWidth(v BorderWidthVal) css.Decl {
	return css.Set(BorderWidth, css.Keyword(string(v)))
}

// SetBottom creates a declaration for the bottom property.
func SetBottom(v BottomVal) css.Decl {
	return css.Set(Bottom, css.Keyword(string(v)))
}

// SetBoxAlign creates a declaration for the box-align property.
func SetBoxAlign(v BoxAlignVal) css.Decl {
	return css.Set(BoxAlign, css.Keyword(string(v)))
}

// SetBoxDecorationBreak creates a declaration for the box-decoration-break property.
func SetBoxDecorationBreak(v BoxDecorationBreakVal) css.Decl {
	return css.Set(BoxDecorationBreak, css.Keyword(string(v)))
}

// SetBoxDirection creates a declaration for the box-direction property.
func SetBoxDirection(v BoxDirectionVal) css.Decl {
	return css.Set(BoxDirection, css.Keyword(string(v)))
}

// SetBoxFlexGroup creates a declaration for the box-flex-group property.
func SetBoxFlexGroup(v BoxFlexGroupVal) css.Decl {
	return css.Set(BoxFlexGroup, css.Keyword(string(v)))
}

// SetBoxLines creates a declaration for the box-lines property.
func SetBoxLines(v BoxLinesVal) css.Decl {
	return css.Set(BoxLines, css.Keyword(string(v)))
}

// SetBoxOrdinalGroup creates a declaration for the box-ordinal-group property.
func SetBoxOrdinalGroup(v BoxOrdinalGroupVal) css.Decl {
	return css.Set(BoxOrdinalGroup, css.Keyword(string(v)))
}

// SetBoxOrient creates a declaration for the box-orient property.
func SetBoxOrient(v BoxOrientVal) css.Decl {
	return css.Set(BoxOrient, css.Keyword(string(v)))
}

// SetBoxPack creates a declaration for the box-pack property.
func SetBoxPack(v BoxPackVal) css.Decl {
	return css.Set(BoxPack, css.Keyword(string(v)))
}

// SetBoxShadow creates a declaration for the box-shadow property.
func SetBoxShadow(v BoxShadowVal) css.Decl {
	return css.Set(BoxShadow, css.Keyword(string(v)))
}

// SetBoxSizing creates a declaration for the box-sizing property.
func SetBoxSizing(v BoxSizingVal) css.Decl {
	return css.Set(BoxSizing, css.Keyword(string(v)))
}

// SetBreakAfter creates a declaration for the break-after property.
func SetBreakAfter(v BreakAfterVal) css.Decl {
	return css.Set(BreakAfter, css.Keyword(string(v)))
}

// SetBreakBefore creates a declaration for the break-before property.
func SetBreakBefore(v BreakBeforeVal) css.Decl {
	return css.Set(BreakBefore, css.Keyword(string(v)))
}

// SetBreakInside creates a declaration for the break-inside property.
func SetBreakInside(v BreakInsideVal) css.Decl {
	return css.Set(BreakInside, css.Keyword(string(v)))
}

// SetCaptionSide creates a declaration for the caption-side property.
func SetCaptionSide(v CaptionSideVal) css.Decl {
	return css.Set(CaptionSide, css.Keyword(string(v)))
}

// SetCaret creates a declaration for the caret property.
func SetCaret(v CaretVal) css.Decl {
	return css.Set(Caret, css.Keyword(string(v)))
}

// SetCaretColor creates a declaration for the caret-color property.
func SetCaretColor(v CaretColorVal) css.Decl {
	return css.Set(CaretColor, css.Keyword(string(v)))
}

// SetCaretShape creates a declaration for the caret-shape property.
func SetCaretShape(v CaretShapeVal) css.Decl {
	return css.Set(CaretShape, css.Keyword(string(v)))
}

// SetClear creates a declaration for the clear property.
func SetClear(v ClearVal) css.Decl {
	return css.Set(Clear, css.Keyword(string(v)))
}

// SetClip creates a declaration for the clip property.
func SetClip(v ClipVal) css.Decl {
	return css.Set(Clip, css.Keyword(string(v)))
}

// SetClipPath creates a declaration for the clip-path property.
func SetClipPath(v ClipPathVal) css.Decl {
	return css.Set(ClipPath, css.Keyword(string(v)))
}

// SetClipRule creates a declaration for the clip-rule property.
func SetClipRule(v ClipRuleVal) css.Decl {
	return css.Set(ClipRule, css.Keyword(string(v)))
}

// SetColor creates a declaration for the color property.
func SetColor(v ColorVal) css.Decl {
	return css.Set(Color, css.Keyword(string(v)))
}

// SetColorInterpolationFilters creates a declaration for the color-interpolation-filters property.
func SetColorInterpolationFilters(v ColorInterpolationFiltersVal) css.Decl {
	return css.Set(ColorInterpolationFilters, css.Keyword(string(v)))
}

// SetColorScheme creates a declaration for the color-scheme property.
func SetColorScheme(v ColorSchemeVal) css.Decl {
	return css.Set(ColorScheme, css.Keyword(string(v)))
}

// SetColumnCount creates a declaration for the column-count property.
func SetColumnCount(v ColumnCountVal) css.Decl {
	return css.Set(ColumnCount, css.Keyword(string(v)))
}

// SetColumnFill creates a declaration for the column-fill property.
func SetColumnFill(v ColumnFillVal) css.Decl {
	return css.Set(ColumnFill, css.Keyword(string(v)))
}

// SetColumnGap creates a declaration for the column-gap property.
func SetColumnGap(v ColumnGapVal) css.Decl {
	return css.Set(ColumnGap, css.Keyword(string(v)))
}

// SetColumnRule creates a declaration for the column-rule property.
func SetColumnRule(v ColumnRuleVal) css.Decl {
	return css.Set(ColumnRule, css.Keyword(string(v)))
}

// SetColumnRuleColor creates a declaration for the column-rule-color property.
func SetColumnRuleColor(v ColumnRuleColorVal) css.Decl {
	return css.Set(ColumnRuleColor, css.Keyword(string(v)))
}

// SetColumnRuleStyle creates a declaration for the column-rule-style property.
func SetColumnRuleStyle(v ColumnRuleStyleVal) css.Decl {
	return css.Set(ColumnRuleStyle, css.Keyword(string(v)))
}

// SetColumnRuleWidth creates a declaration for the column-rule-width property.
func SetColumnRuleWidth(v ColumnRuleWidthVal) css.Decl {
	return css.Set(ColumnRuleWidth, css.Keyword(string(v)))
}

// SetColumnSpan creates a declaration for the column-span property.
func SetColumnSpan(v ColumnSpanVal) css.Decl {
	return css.Set(ColumnSpan, css.Keyword(string(v)))
}

// SetColumnWidth creates a declaration for the column-width property.
func SetColumnWidth(v ColumnWidthVal) css.Decl {
	return css.Set(ColumnWidth, css.Keyword(string(v)))
}

// SetColumns creates a declaration for the columns property.
func SetColumns(v ColumnsVal) css.Decl {
	return css.Set(Columns, css.Keyword(string(v)))
}

// SetContain creates a declaration for the contain property.
func SetContain(v ContainVal) css.Decl {
	return css.Set(Contain, css.Keyword(string(v)))
}

// SetContainIntrinsicBlockSize creates a declaration for the contain-intrinsic-block-size property.
func SetContainIntrinsicBlockSize(v ContainIntrinsicBlockSizeVal) css.Decl {
	return css.Set(ContainIntrinsicBlockSize, css.Keyword(string(v)))
}

// SetContainIntrinsicHeight creates a declaration for the contain-intrinsic-height property.
func SetContainIntrinsicHeight(v ContainIntrinsicHeightVal) css.Decl {
	return css.Set(ContainIntrinsicHeight, css.Keyword(string(v)))
}

// SetContainIntrinsicInlineSize creates a declaration for the contain-intrinsic-inline-size property.
func SetContainIntrinsicInlineSize(v ContainIntrinsicInlineSizeVal) css.Decl {
	return css.Set(ContainIntrinsicInlineSize, css.Keyword(string(v)))
}

// SetContainIntrinsicSize creates a declaration for the contain-intrinsic-size property.
func SetContainIntrinsicSize(v ContainIntrinsicSizeVal) css.Decl {
	return css.Set(ContainIntrinsicSize, css.Keyword(string(v)))
}

// SetContainIntrinsicWidth creates a declaration for the contain-intrinsic-width property.
func SetContainIntrinsicWidth(v ContainIntrinsicWidthVal) css.Decl {
	return css.Set(ContainIntrinsicWidth, css.Keyword(string(v)))
}

// SetContainer creates a declaration for the container property.
func SetContainer(v ContainerVal) css.Decl {
	return css.Set(Container, css.Keyword(string(v)))
}

// SetContainerName creates a declaration for the container-name property.
func SetContainerName(v ContainerNameVal) css.Decl {
	return css.Set(ContainerName, css.Keyword(string(v)))
}

// SetContainerType creates a declaration for the container-type property.
func SetContainerType(v ContainerTypeVal) css.Decl {
	return css.Set(ContainerType, css.Keyword(string(v)))
}

// SetContent creates a declaration for the content property.
func SetContent(v ContentVal) css.Decl {
	return css.Set(Content, css.Keyword(string(v)))
}

// SetContentVisibility creates a declaration for the content-visibility property.
func SetContentVisibility(v ContentVisibilityVal) css.Decl {
	return css.Set(ContentVisibility, css.Keyword(string(v)))
}

// SetCounterIncrement creates a declaration for the counter-increment property.
func SetCounterIncrement(v CounterIncrementVal) css.Decl {
	return css.Set(CounterIncrement, css.Keyword(string(v)))
}

// SetCounterReset creates a declaration for the counter-reset property.
func SetCounterReset(v CounterResetVal) css.Decl {
	return css.Set(CounterReset, css.Keyword(string(v)))
}

// SetCounterSet creates a declaration for the counter-set property.
func SetCounterSet(v CounterSetVal) css.Decl {
	return css.Set(CounterSet, css.Keyword(string(v)))
}

// SetCursor creates a declaration for the cursor property.
func SetCursor(v CursorVal) css.Decl {
	return css.Set(Cursor, css.Keyword(string(v)))
}

// SetD creates a declaration for the d property.
func SetD(v DVal) css.Decl {
	return css.Set(D, css.Keyword(string(v)))
}

// SetDirection creates a declaration for the direction property.
func SetDirection(v DirectionVal) css.Decl {
	return css.Set(Direction, css.Keyword(string(v)))
}

// SetDisplay creates a declaration for the display property.
func SetDisplay(v DisplayVal) css.Decl {
	return css.Set(Display, css.Keyword(string(v)))
}

// SetDominantBaseline creates a declaration for the dominant-baseline property.
func SetDominantBaseline(v DominantBaselineVal) css.Decl {
	return css.Set(DominantBaseline, css.Keyword(string(v)))
}

// SetEmptyCells creates a declaration for the empty-cells property.
func SetEmptyCells(v EmptyCellsVal) css.Decl {
	return css.Set(EmptyCells, css.Keyword(string(v)))
}

// SetFill creates a declaration for the fill property.
func SetFill(v FillVal) css.Decl {
	return css.Set(Fill, css.Keyword(string(v)))
}

// SetFillOpacity creates a declaration for the fill-opacity property.
func SetFillOpacity(v FillOpacityVal) css.Decl {
	return css.Set(FillOpacity, css.Keyword(string(v)))
}

// SetFillRule creates a declaration for the fill-rule property.
func SetFillRule(v FillRuleVal) css.Decl {
	return css.Set(FillRule, css.Keyword(string(v)))
}

// SetFilter creates a declaration for the filter property.
func SetFilter(v FilterVal) css.Decl {
	return css.Set(Filter, css.Keyword(string(v)))
}

// SetFlex creates a declaration for the flex property.
func SetFlex(v FlexVal) css.Decl {
	return css.Set(Flex, css.Keyword(string(v)))
}

// SetFlexBasis creates a declaration for the flex-basis property.
func SetFlexBasis(v FlexBasisVal) css.Decl {
	return css.Set(FlexBasis, css.Keyword(string(v)))
}

// SetFlexDirection creates a declaration for the flex-direction property.
func SetFlexDirection(v FlexDirectionVal) css.Decl {
	return css.Set(FlexDirection, css.Keyword(string(v)))
}

// SetFlexFlow creates a declaration for the flex-flow property.
func SetFlexFlow(v FlexFlowVal) css.Decl {
	return css.Set(FlexFlow, css.Keyword(string(v)))
}

// SetFlexWrap creates a declaration for the flex-wrap property.
func SetFlexWrap(v FlexWrapVal) css.Decl {
	return css.Set(FlexWrap, css.Keyword(string(v)))
}

// SetFloat creates a declaration for the float property.
func SetFloat(v FloatVal) css.Decl {
	return css.Set(Float, css.Keyword(string(v)))
}

// SetFloodColor creates a declaration for the flood-color property.
func SetFloodColor(v FloodColorVal) css.Decl {
	return css.Set(FloodColor, css.Keyword(string(v)))
}

// SetFloodOpacity creates a declaration for the flood-opacity property.
func SetFloodOpacity(v FloodOpacityVal) css.Decl {
	return css.Set(FloodOpacity, css.Keyword(string(v)))
}

// SetFont creates a declaration for the font property.
func SetFont(v FontVal) css.Decl {
	return css.Set(Font, css.Keyword(string(v)))
}

// SetFontFamily creates a declaration for the font-family property.
func SetFontFamily(v FontFamilyVal) css.Decl {
	return css.Set(FontFamily, css.Keyword(string(v)))
}

// SetFontFeatureSettings creates a declaration for the font-feature-settings property.
func SetFontFeatureSettings(v FontFeatureSettingsVal) css.Decl {
	return css.Set(FontFeatureSettings, css.Keyword(string(v)))
}

// SetFontKerning creates a declaration for the font-kerning property.
func SetFontKerning(v FontKerningVal) css.Decl {
	return css.Set(FontKerning, css.Keyword(string(v)))
}

// SetFontLanguageOverride creates a declaration for the font-language-override property.
func SetFontLanguageOverride(v FontLanguageOverrideVal) css.Decl {
	return css.Set(FontLanguageOverride, css.Keyword(string(v)))
}

// SetFontOpticalSizing creates a declaration for the font-optical-sizing property.
func SetFontOpticalSizing(v FontOpticalSizingVal) css.Decl {
	return css.Set(FontOpticalSizing, css.Keyword(string(v)))
}

// SetFontPalette creates a declaration for the font-palette property.
func SetFontPalette(v FontPaletteVal) css.Decl {
	return css.Set(FontPalette, css.Keyword(string(v)))
}

// SetFontSize creates a declaration for the font-size property.
func SetFontSize(v FontSizeVal) css.Decl {
	return css.Set(FontSize, css.Keyword(string(v)))
}

// SetFontSizeAdjust creates a declaration for the font-size-adjust property.
func SetFontSizeAdjust(v FontSizeAdjustVal) css.Decl {
	return css.Set(FontSizeAdjust, css.Keyword(string(v)))
}

// SetFontSmooth creates a declaration for the font-smooth property.
func SetFontSmooth(v FontSmoothVal) css.Decl {
	return css.Set(FontSmooth, css.Keyword(string(v)))
}

// SetFontStretch creates a declaration for the font-stretch property.
func SetFontStretch(v FontStretchVal) css.Decl {
	return css.Set(FontStretch, css.Keyword(string(v)))
}

// SetFontStyle creates a declaration for the font-style property.
func SetFontStyle(v FontStyleVal) css.Decl {
	return css.Set(FontStyle, css.Keyword(string(v)))
}

// SetFontSynthesis creates a declaration for the font-synthesis property.
func SetFontSynthesis(v FontSynthesisVal) css.Decl {
	return css.Set(FontSynthesis, css.Keyword(string(v)))
}

// SetFontSynthesisSmallCaps creates a declaration for the font-synthesis-small-caps property.
func SetFontSynthesisSmallCaps(v FontSynthesisSmallCapsVal) css.Decl {
	return css.Set(FontSynthesisSmallCaps, css.Keyword(string(v)))
}

// SetFontSynthesisStyle creates a declaration for the font-synthesis-style property.
func SetFontSynthesisStyle(v FontSynthesisStyleVal) css.Decl {
	return css.Set(FontSynthesisStyle, css.Keyword(string(v)))
}

// SetFontSynthesisWeight creates a declaration for the font-synthesis-weight property.
func SetFontSynthesisWeight(v FontSynthesisWeightVal) css.Decl {
	return css.Set(FontSynthesisWeight, css.Keyword(string(v)))
}

// SetFontVariant creates a declaration for the font-variant property.
func SetFontVariant(v FontVariantVal) css.Decl {
	return css.Set(FontVariant, css.Keyword(string(v)))
}

// SetFontVariantAlternates creates a declaration for the font-variant-alternates property.
func SetFontVariantAlternates(v FontVariantAlternatesVal) css.Decl {
	return css.Set(FontVariantAlternates, css.Keyword(string(v)))
}

// SetFontVariantCaps creates a declaration for the font-variant-caps property.
func SetFontVariantCaps(v FontVariantCapsVal) css.Decl {
	return css.Set(FontVariantCaps, css.Keyword(string(v)))
}

// SetFontVariantEastAsian creates a declaration for the font-variant-east-asian property.
func SetFontVariantEastAsian(v FontVariantEastAsianVal) css.Decl {
	return css.Set(FontVariantEastAsian, css.Keyword(string(v)))
}

// SetFontVariantEmoji creates a declaration for the font-variant-emoji property.
func SetFontVariantEmoji(v FontVariantEmojiVal) css.Decl {
	return css.Set(FontVariantEmoji, css.Keyword(string(v)))
}

// SetFontVariantLigatures creates a declaration for the font-variant-ligatures property.
func SetFontVariantLigatures(v FontVariantLigaturesVal) css.Decl {
	return css.Set(FontVariantLigatures, css.Keyword(string(v)))
}

// SetFontVariantNumeric creates a declaration for the font-variant-numeric property.
func SetFontVariantNumeric(v FontVariantNumericVal) css.Decl {
	return css.Set(FontVariantNumeric, css.Keyword(string(v)))
}

// SetFontVariantPosition creates a declaration for the font-variant-position property.
func SetFontVariantPosition(v FontVariantPositionVal) css.Decl {
	return css.Set(FontVariantPosition, css.Keyword(string(v)))
}

// SetFontVariationSettings creates a declaration for the font-variation-settings property.
func SetFontVariationSettings(v FontVariationSettingsVal) css.Decl {
	return css.Set(FontVariationSettings, css.Keyword(string(v)))
}

// SetFontWeight creates a declaration for the font-weight property.
func SetFontWeight(v FontWeightVal) css.Decl {
	return css.Set(FontWeight, css.Keyword(string(v)))
}

// SetForcedColorAdjust creates a declaration for the forced-color-adjust property.
func SetForcedColorAdjust(v ForcedColorAdjustVal) css.Decl {
	return css.Set(ForcedColorAdjust, css.Keyword(string(v)))
}

// SetGap creates a declaration for the gap property.
func SetGap(v GapVal) css.Decl {
	return css.Set(Gap, css.Keyword(string(v)))
}

// SetGrid creates a declaration for the grid property.
func SetGrid(v GridVal) css.Decl {
	return css.Set(Grid, css.Keyword(string(v)))
}

// SetGridArea creates a declaration for the grid-area property.
func SetGridArea(v GridAreaVal) css.Decl {
	return css.Set(GridArea, css.Keyword(string(v)))
}

// SetGridAutoColumns creates a declaration for the grid-auto-columns property.
func SetGridAutoColumns(v GridAutoColumnsVal) css.Decl {
	return css.Set(GridAutoColumns, css.Keyword(string(v)))
}

// SetGridAutoFlow creates a declaration for the grid-auto-flow property.
func SetGridAutoFlow(v GridAutoFlowVal) css.Decl {
	return css.Set(GridAutoFlow, css.Keyword(string(v)))
}

// SetGridAutoRows creates a declaration for the grid-auto-rows property.
func SetGridAutoRows(v GridAutoRowsVal) css.Decl {
	return css.Set(GridAutoRows, css.Keyword(string(v)))
}

// SetGridColumn creates a declaration for the grid-column property.
func SetGridColumn(v GridColumnVal) css.Decl {
	return css.Set(GridColumn, css.Keyword(string(v)))
}

// SetGridColumnEnd creates a declaration for the grid-column-end property.
func SetGridColumnEnd(v GridColumnEndVal) css.Decl {
	return css.Set(GridColumnEnd, css.Keyword(string(v)))
}

// SetGridColumnStart creates a declaration for the grid-column-start property.
func SetGridColumnStart(v GridColumnStartVal) css.Decl {
	return css.Set(GridColumnStart, css.Keyword(string(v)))
}

// SetGridGap creates a declaration for the grid-gap property.
func SetGridGap(v GridGapVal) css.Decl {
	return css.Set(GridGap, css.Keyword(string(v)))
}

// SetGridRow creates a declaration for the grid-row property.
func SetGridRow(v GridRowVal) css.Decl {
	return css.Set(GridRow, css.Keyword(string(v)))
}

// SetGridRowEnd creates a declaration for the grid-row-end property.
func SetGridRowEnd(v GridRowEndVal) css.Decl {
	return css.Set(GridRowEnd, css.Keyword(string(v)))
}

// SetGridRowStart creates a declaration for the grid-row-start property.
func SetGridRowStart(v GridRowStartVal) css.Decl {
	return css.Set(GridRowStart, css.Keyword(string(v)))
}

// SetGridTemplate creates a declaration for the grid-template property.
func SetGridTemplate(v GridTemplateVal) css.Decl {
	return css.Set(GridTemplate, css.Keyword(string(v)))
}

// SetGridTemplateAreas creates a declaration for the grid-template-areas property.
func SetGridTemplateAreas(v GridTemplateAreasVal) css.Decl {
	return css.Set(GridTemplateAreas, css.Keyword(string(v)))
}

// SetGridTemplateColumns creates a declaration for the grid-template-columns property.
func SetGridTemplateColumns(v GridTemplateColumnsVal) css.Decl {
	return css.Set(GridTemplateColumns, css.Keyword(string(v)))
}

// SetGridTemplateRows creates a declaration for the grid-template-rows property.
func SetGridTemplateRows(v GridTemplateRowsVal) css.Decl {
	return css.Set(GridTemplateRows, css.Keyword(string(v)))
}

// SetHangingPunctuation creates a declaration for the hanging-punctuation property.
func SetHangingPunctuation(v HangingPunctuationVal) css.Decl {
	return css.Set(HangingPunctuation, css.Keyword(string(v)))
}

// SetHeight creates a declaration for the height property.
func SetHeight(v HeightVal) css.Decl {
	return css.Set(Height, css.Keyword(string(v)))
}

// SetHyphenateCharacter creates a declaration for the hyphenate-character property.
func SetHyphenateCharacter(v HyphenateCharacterVal) css.Decl {
	return css.Set(HyphenateCharacter, css.Keyword(string(v)))
}

// SetHyphenateLimitChars creates a declaration for the hyphenate-limit-chars property.
func SetHyphenateLimitChars(v HyphenateLimitCharsVal) css.Decl {
	return css.Set(HyphenateLimitChars, css.Keyword(string(v)))
}

// SetHyphens creates a declaration for the hyphens property.
func SetHyphens(v HyphensVal) css.Decl {
	return css.Set(Hyphens, css.Keyword(string(v)))
}

// SetImageOrientation creates a declaration for the image-orientation property.
func SetImageOrientation(v ImageOrientationVal) css.Decl {
	return css.Set(ImageOrientation, css.Keyword(string(v)))
}

// SetImageRendering creates a declaration for the image-rendering property.
func SetImageRendering(v ImageRenderingVal) css.Decl {
	return css.Set(ImageRendering, css.Keyword(string(v)))
}

// SetImeMode creates a declaration for the ime-mode property.
func SetImeMode(v ImeModeVal) css.Decl {
	return css.Set(ImeMode, css.Keyword(string(v)))
}

// SetInitialLetter creates a declaration for the initial-letter property.
func SetInitialLetter(v InitialLetterVal) css.Decl {
	return css.Set(InitialLetter, css.Keyword(string(v)))
}

// SetInlineSize creates a declaration for the inline-size property.
func SetInlineSize(v InlineSizeVal) css.Decl {
	return css.Set(InlineSize, css.Keyword(string(v)))
}

// SetInset creates a declaration for the inset property.
func SetInset(v InsetVal) css.Decl {
	return css.Set(Inset, css.Keyword(string(v)))
}

// SetInsetBlock creates a declaration for the inset-block property.
func SetInsetBlock(v InsetBlockVal) css.Decl {
	return css.Set(InsetBlock, css.Keyword(string(v)))
}

// SetInsetBlockEnd creates a declaration for the inset-block-end property.
func SetInsetBlockEnd(v InsetBlockEndVal) css.Decl {
	return css.Set(InsetBlockEnd, css.Keyword(string(v)))
}

// SetInsetBlockStart creates a declaration for the inset-block-start property.
func SetInsetBlockStart(v InsetBlockStartVal) css.Decl {
	return css.Set(InsetBlockStart, css.Keyword(string(v)))
}

// SetInsetInline creates a declaration for the inset-inline property.
func SetInsetInline(v InsetInlineVal) css.Decl {
	return css.Set(InsetInline, css.Keyword(string(v)))
}

// SetInsetInlineEnd creates a declaration for the inset-inline-end property.
func SetInsetInlineEnd(v InsetInlineEndVal) css.Decl {
	return css.Set(InsetInlineEnd, css.Keyword(string(v)))
}

// SetInsetInlineStart creates a declaration for the inset-inline-start property.
func SetInsetInlineStart(v InsetInlineStartVal) css.Decl {
	return css.Set(InsetInlineStart, css.Keyword(string(v)))
}

// SetIsolation creates a declaration for the isolation property.
func SetIsolation(v IsolationVal) css.Decl {
	return css.Set(Isolation, css.Keyword(string(v)))
}

// SetJustifyContent creates a declaration for the justify-content property.
func SetJustifyContent(v JustifyContentVal) css.Decl {
	return css.Set(JustifyContent, css.Keyword(string(v)))
}

// SetJustifyItems creates a declaration for the justify-items property.
func SetJustifyItems(v JustifyItemsVal) css.Decl {
	return css.Set(JustifyItems, css.Keyword(string(v)))
}

// SetJustifySelf creates a declaration for the justify-self property.
func SetJustifySelf(v JustifySelfVal) css.Decl {
	return css.Set(JustifySelf, css.Keyword(string(v)))
}

// SetJustifyTracks creates a declaration for the justify-tracks property.
func SetJustifyTracks(v JustifyTracksVal) css.Decl {
	return css.Set(JustifyTracks, css.Keyword(string(v)))
}

// SetLeft creates a declaration for the left property.
func SetLeft(v LeftVal) css.Decl {
	return css.Set(Left, css.Keyword(string(v)))
}

// SetLetterSpacing creates a declaration for the letter-spacing property.
func SetLetterSpacing(v LetterSpacingVal) css.Decl {
	return css.Set(LetterSpacing, css.Keyword(string(v)))
}

// SetLightingColor creates a declaration for the lighting-color property.
func SetLightingColor(v LightingColorVal) css.Decl {
	return css.Set(LightingColor, css.Keyword(string(v)))
}

// SetLineBreak creates a declaration for the line-break property.
func SetLineBreak(v LineBreakVal) css.Decl {
	return css.Set(LineBreak, css.Keyword(string(v)))
}

// SetLineClamp creates a declaration for the line-clamp property.
func SetLineClamp(v LineClampVal) css.Decl {
	return css.Set(LineClamp, css.Keyword(string(v)))
}

// SetLineHeight creates a declaration for the line-height property.
func SetLineHeight(v LineHeightVal) css.Decl {
	return css.Set(LineHeight, css.Keyword(string(v)))
}

// SetListStyle creates a declaration for the list-style property.
func SetListStyle(v ListStyleVal) css.Decl {
	return css.Set(ListStyle, css.Keyword(string(v)))
}

// SetListStyleImage creates a declaration for the list-style-image property.
func SetListStyleImage(v ListStyleImageVal) css.Decl {
	return css.Set(ListStyleImage, css.Keyword(string(v)))
}

// SetListStylePosition creates a declaration for the list-style-position property.
func SetListStylePosition(v ListStylePositionVal) css.Decl {
	return css.Set(ListStylePosition, css.Keyword(string(v)))
}

// SetListStyleType creates a declaration for the list-style-type property.
func SetListStyleType(v ListStyleTypeVal) css.Decl {
	return css.Set(ListStyleType, css.Keyword(string(v)))
}

// SetMargin creates a declaration for the margin property.
func SetMargin(v MarginVal) css.Decl {
	return css.Set(Margin, css.Keyword(string(v)))
}

// SetMarginBlock creates a declaration for the margin-block property.
func SetMarginBlock(v MarginBlockVal) css.Decl {
	return css.Set(MarginBlock, css.Keyword(string(v)))
}

// SetMarginBlockEnd creates a declaration for the margin-block-end property.
func SetMarginBlockEnd(v MarginBlockEndVal) css.Decl {
	return css.Set(MarginBlockEnd, css.Keyword(string(v)))
}

// SetMarginBlockStart creates a declaration for the margin-block-start property.
func SetMarginBlockStart(v MarginBlockStartVal) css.Decl {
	return css.Set(MarginBlockStart, css.Keyword(string(v)))
}

// SetMarginBottom creates a declaration for the margin-bottom property.
func SetMarginBottom(v MarginBottomVal) css.Decl {
	return css.Set(MarginBottom, css.Keyword(string(v)))
}

// SetMarginInline creates a declaration for the margin-inline property.
func SetMarginInline(v MarginInlineVal) css.Decl {
	return css.Set(MarginInline, css.Keyword(string(v)))
}

// SetMarginInlineEnd creates a declaration for the margin-inline-end property.
func SetMarginInlineEnd(v MarginInlineEndVal) css.Decl {
	return css.Set(MarginInlineEnd, css.Keyword(string(v)))
}

// SetMarginInlineStart creates a declaration for the margin-inline-start property.
func SetMarginInlineStart(v MarginInlineStartVal) css.Decl {
	return css.Set(MarginInlineStart, css.Keyword(string(v)))
}

// SetMarginLeft creates a declaration for the margin-left property.
func SetMarginLeft(v MarginLeftVal) css.Decl {
	return css.Set(MarginLeft, css.Keyword(string(v)))
}

// SetMarginRight creates a declaration for the margin-right property.
func SetMarginRight(v MarginRightVal) css.Decl {
	return css.Set(MarginRight, css.Keyword(string(v)))
}

// SetMarginTop creates a declaration for the margin-top property.
func SetMarginTop(v MarginTopVal) css.Decl {
	return css.Set(MarginTop, css.Keyword(string(v)))
}

// SetMarker creates a declaration for the marker property.
func SetMarker(v MarkerVal) css.Decl {
	return css.Set(Marker, css.Keyword(string(v)))
}

// SetMarkerEnd creates a declaration for the marker-end property.
func SetMarkerEnd(v MarkerEndVal) css.Decl {
	return css.Set(MarkerEnd, css.Keyword(string(v)))
}

// SetMarkerMid creates a declaration for the marker-mid property.
func SetMarkerMid(v MarkerMidVal) css.Decl {
	return css.Set(MarkerMid, css.Keyword(string(v)))
}

// SetMarkerStart creates a declaration for the marker-start property.
func SetMarkerStart(v MarkerStartVal) css.Decl {
	return css.Set(MarkerStart, css.Keyword(string(v)))
}

// SetMask creates a declaration for the mask property.
func SetMask(v MaskVal) css.Decl {
	return css.Set(Mask, css.Keyword(string(v)))
}

// SetMaskBorder creates a declaration for the mask-border property.
func SetMaskBorder(v MaskBorderVal) css.Decl {
	return css.Set(MaskBorder, css.Keyword(string(v)))
}

// SetMaskBorderMode creates a declaration for the mask-border-mode property.
func SetMaskBorderMode(v MaskBorderModeVal) css.Decl {
	return css.Set(MaskBorderMode, css.Keyword(string(v)))
}

// SetMaskBorderOutset creates a declaration for the mask-border-outset property.
func SetMaskBorderOutset(v MaskBorderOutsetVal) css.Decl {
	return css.Set(MaskBorderOutset, css.Keyword(string(v)))
}

// SetMaskBorderRepeat creates a declaration for the mask-border-repeat property.
func SetMaskBorderRepeat(v MaskBorderRepeatVal) css.Decl {
	return css.Set(MaskBorderRepeat, css.Keyword(string(v)))
}

// SetMaskBorderSlice creates a declaration for the mask-border-slice property.
func SetMaskBorderSlice(v MaskBorderSliceVal) css.Decl {
	return css.Set(MaskBorderSlice, css.Keyword(string(v)))
}

// SetMaskBorderSource creates a declaration for the mask-border-source property.
func SetMaskBorderSource(v MaskBorderSourceVal) css.Decl {
	return css.Set(MaskBorderSource, css.Keyword(string(v)))
}

// SetMaskBorderWidth creates a declaration for the mask-border-width property.
func SetMaskBorderWidth(v MaskBorderWidthVal) css.Decl {
	return css.Set(MaskBorderWidth, css.Keyword(string(v)))
}

// SetMaskClip creates a declaration for the mask-clip property.
func SetMaskClip(v MaskClipVal) css.Decl {
	return css.Set(MaskClip, css.Keyword(string(v)))
}

// SetMaskComposite creates a declaration for the mask-composite property.
func SetMaskComposite(v MaskCompositeVal) css.Decl {
	return css.Set(MaskComposite, css.Keyword(string(v)))
}

// SetMaskImage creates a declaration for the mask-image property.
func SetMaskImage(v MaskImageVal) css.Decl {
	return css.Set(MaskImage, css.Keyword(string(v)))
}

// SetMaskMode creates a declaration for the mask-mode property.
func SetMaskMode(v MaskModeVal) css.Decl {
	return css.Set(MaskMode, css.Keyword(string(v)))
}

// SetMaskOrigin creates a declaration for the mask-origin property.
func SetMaskOrigin(v MaskOriginVal) css.Decl {
	return css.Set(MaskOrigin, css.Keyword(string(v)))
}

// SetMaskPosition creates a declaration for the mask-position property.
func SetMaskPosition(v MaskPositionVal) css.Decl {
	return css.Set(MaskPosition, css.Keyword(string(v)))
}

// SetMaskRepeat creates a declaration for the mask-repeat property.
func SetMaskRepeat(v MaskRepeatVal) css.Decl {
	return css.Set(MaskRepeat, css.Keyword(string(v)))
}

// SetMaskSize creates a declaration for the mask-size property.
func SetMaskSize(v MaskSizeVal) css.Decl {
	return css.Set(MaskSize, css.Keyword(string(v)))
}

// SetMaskType creates a declaration for the mask-type property.
func SetMaskType(v MaskTypeVal) css.Decl {
	return css.Set(MaskType, css.Keyword(string(v)))
}

// SetMasonryAutoFlow creates a declaration for the masonry-auto-flow property.
func SetMasonryAutoFlow(v MasonryAutoFlowVal) css.Decl {
	return css.Set(MasonryAutoFlow, css.Keyword(string(v)))
}

// SetMathDepth creates a declaration for the math-depth property.
func SetMathDepth(v MathDepthVal) css.Decl {
	return css.Set(MathDepth, css.Keyword(string(v)))
}

// SetMathStyle creates a declaration for the math-style property.
func SetMathStyle(v MathStyleVal) css.Decl {
	return css.Set(MathStyle, css.Keyword(string(v)))
}

// SetMaxBlockSize creates a declaration for the max-block-size property.
func SetMaxBlockSize(v MaxBlockSizeVal) css.Decl {
	return css.Set(MaxBlockSize, css.Keyword(string(v)))
}

// SetMaxHeight creates a declaration for the max-height property.
func SetMaxHeight(v MaxHeightVal) css.Decl {
	return css.Set(MaxHeight, css.Keyword(string(v)))
}

// SetMaxInlineSize creates a declaration for the max-inline-size property.
func SetMaxInlineSize(v MaxInlineSizeVal) css.Decl {
	return css.Set(MaxInlineSize, css.Keyword(string(v)))
}

// SetMaxWidth creates a declaration for the max-width property.
func SetMaxWidth(v MaxWidthVal) css.Decl {
	return css.Set(MaxWidth, css.Keyword(string(v)))
}

// SetMinBlockSize creates a declaration for the min-block-size property.
func SetMinBlockSize(v MinBlockSizeVal) css.Decl {
	return css.Set(MinBlockSize, css.Keyword(string(v)))
}

// SetMinHeight creates a declaration for the min-height property.
func SetMinHeight(v MinHeightVal) css.Decl {
	return css.Set(MinHeight, css.Keyword(string(v)))
}

// SetMinInlineSize creates a declaration for the min-inline-size property.
func SetMinInlineSize(v MinInlineSizeVal) css.Decl {
	return css.Set(MinInlineSize, css.Keyword(string(v)))
}

// SetMinWidth creates a declaration for the min-width property.
func SetMinWidth(v MinWidthVal) css.Decl {
	return css.Set(MinWidth, css.Keyword(string(v)))
}

// SetMixBlendMode creates a declaration for the mix-blend-mode property.
func SetMixBlendMode(v MixBlendModeVal) css.Decl {
	return css.Set(MixBlendMode, css.Keyword(string(v)))
}

// SetObjectFit creates a declaration for the object-fit property.
func SetObjectFit(v ObjectFitVal) css.Decl {
	return css.Set(ObjectFit, css.Keyword(string(v)))
}

// SetObjectPosition creates a declaration for the object-position property.
func SetObjectPosition(v ObjectPositionVal) css.Decl {
	return css.Set(ObjectPosition, css.Keyword(string(v)))
}

// SetOffset creates a declaration for the offset property.
func SetOffset(v OffsetVal) css.Decl {
	return css.Set(Offset, css.Keyword(string(v)))
}

// SetOffsetAnchor creates a declaration for the offset-anchor property.
func SetOffsetAnchor(v OffsetAnchorVal) css.Decl {
	return css.Set(OffsetAnchor, css.Keyword(string(v)))
}

// SetOffsetPath creates a declaration for the offset-path property.
func SetOffsetPath(v OffsetPathVal) css.Decl {
	return css.Set(OffsetPath, css.Keyword(string(v)))
}

// SetOffsetPosition creates a declaration for the offset-position property.
func SetOffsetPosition(v OffsetPositionVal) css.Decl {
	return css.Set(OffsetPosition, css.Keyword(string(v)))
}

// SetOffsetRotate creates a declaration for the offset-rotate property.
func SetOffsetRotate(v OffsetRotateVal) css.Decl {
	return css.Set(OffsetRotate, css.Keyword(string(v)))
}

// SetOrder creates a declaration for the order property.
func SetOrder(v OrderVal) css.Decl {
	return css.Set(Order, css.Keyword(string(v)))
}

// SetOrphans creates a declaration for the orphans property.
func SetOrphans(v OrphansVal) css.Decl {
	return css.Set(Orphans, css.Keyword(string(v)))
}

// SetOutline creates a declaration for the outline property.
func SetOutline(v OutlineVal) css.Decl {
	return css.Set(Outline, css.Keyword(string(v)))
}

// SetOutlineColor creates a declaration for the outline-color property.
func SetOutlineColor(v OutlineColorVal) css.Decl {
	return css.Set(OutlineColor, css.Keyword(string(v)))
}

// SetOutlineStyle creates a declaration for the outline-style property.
func SetOutlineStyle(v OutlineStyleVal) css.Decl {
	return css.Set(OutlineStyle, css.Keyword(string(v)))
}

// SetOutlineWidth creates a declaration for the outline-width property.
func SetOutlineWidth(v OutlineWidthVal) css.Decl {
	return css.Set(OutlineWidth, css.Keyword(string(v)))
}

// SetOverflow creates a declaration for the overflow property.
func SetOverflow(v OverflowVal) css.Decl {
	return css.Set(Overflow, css.Keyword(string(v)))
}

// SetOverflowAnchor creates a declaration for the overflow-anchor property.
func SetOverflowAnchor(v OverflowAnchorVal) css.Decl {
	return css.Set(OverflowAnchor, css.Keyword(string(v)))
}

// SetOverflowBlock creates a declaration for the overflow-block property.
func SetOverflowBlock(v OverflowBlockVal) css.Decl {
	return css.Set(OverflowBlock, css.Keyword(string(v)))
}

// SetOverflowClipBox creates a declaration for the overflow-clip-box property.
func SetOverflowClipBox(v OverflowClipBoxVal) css.Decl {
	return css.Set(OverflowClipBox, css.Keyword(string(v)))
}

// SetOverflowClipMargin creates a declaration for the overflow-clip-margin property.
func SetOverflowClipMargin(v OverflowClipMarginVal) css.Decl {
	return css.Set(OverflowClipMargin, css.Keyword(string(v)))
}

// SetOverflowInline creates a declaration for the overflow-inline property.
func SetOverflowInline(v OverflowInlineVal) css.Decl {
	return css.Set(OverflowInline, css.Keyword(string(v)))
}

// SetOverflowWrap creates a declaration for the overflow-wrap property.
func SetOverflowWrap(v OverflowWrapVal) css.Decl {
	return css.Set(OverflowWrap, css.Keyword(string(v)))
}

// SetOverflowX creates a declaration for the overflow-x property.
func SetOverflowX(v OverflowXVal) css.Decl {
	return css.Set(OverflowX, css.Keyword(string(v)))
}

// SetOverflowY creates a declaration for the overflow-y property.
func SetOverflowY(v OverflowYVal) css.Decl {
	return css.Set(OverflowY, css.Keyword(string(v)))
}

// SetOverscrollBehavior creates a declaration for the overscroll-behavior property.
func SetOverscrollBehavior(v OverscrollBehaviorVal) css.Decl {
	return css.Set(OverscrollBehavior, css.Keyword(string(v)))
}

// SetOverscrollBehaviorBlock creates a declaration for the overscroll-behavior-block property.
func SetOverscrollBehaviorBlock(v OverscrollBehaviorBlockVal) css.Decl {
	return css.Set(OverscrollBehaviorBlock, css.Keyword(string(v)))
}

// SetOverscrollBehaviorInline creates a declaration for the overscroll-behavior-inline property.
func SetOverscrollBehaviorInline(v OverscrollBehaviorInlineVal) css.Decl {
	return css.Set(OverscrollBehaviorInline, css.Keyword(string(v)))
}

// SetOverscrollBehaviorX creates a declaration for the overscroll-behavior-x property.
func SetOverscrollBehaviorX(v OverscrollBehaviorXVal) css.Decl {
	return css.Set(OverscrollBehaviorX, css.Keyword(string(v)))
}

// SetOverscrollBehaviorY creates a declaration for the overscroll-behavior-y property.
func SetOverscrollBehaviorY(v OverscrollBehaviorYVal) css.Decl {
	return css.Set(OverscrollBehaviorY, css.Keyword(string(v)))
}

// SetPadding creates a declaration for the padding property.
func SetPadding(v PaddingVal) css.Decl {
	return css.Set(Padding, css.Keyword(string(v)))
}

// SetPaddingBlock creates a declaration for the padding-block property.
func SetPaddingBlock(v PaddingBlockVal) css.Decl {
	return css.Set(PaddingBlock, css.Keyword(string(v)))
}

// SetPaddingBlockEnd creates a declaration for the padding-block-end property.
func SetPaddingBlockEnd(v PaddingBlockEndVal) css.Decl {
	return css.Set(PaddingBlockEnd, css.Keyword(string(v)))
}

// SetPaddingBlockStart creates a declaration for the padding-block-start property.
func SetPaddingBlockStart(v PaddingBlockStartVal) css.Decl {
	return css.Set(PaddingBlockStart, css.Keyword(string(v)))
}

// SetPaddingBottom creates a declaration for the padding-bottom property.
func SetPaddingBottom(v PaddingBottomVal) css.Decl {
	return css.Set(PaddingBottom, css.Keyword(string(v)))
}

// SetPaddingInline creates a declaration for the padding-inline property.
func SetPaddingInline(v PaddingInlineVal) css.Decl {
	return css.Set(PaddingInline, css.Keyword(string(v)))
}

// SetPaddingInlineEnd creates a declaration for the padding-inline-end property.
func SetPaddingInlineEnd(v PaddingInlineEndVal) css.Decl {
	return css.Set(PaddingInlineEnd, css.Keyword(string(v)))
}

// SetPaddingInlineStart creates a declaration for the padding-inline-start property.
func SetPaddingInlineStart(v PaddingInlineStartVal) css.Decl {
	return css.Set(PaddingInlineStart, css.Keyword(string(v)))
}

// SetPaddingLeft creates a declaration for the padding-left property.
func SetPaddingLeft(v PaddingLeftVal) css.Decl {
	return css.Set(PaddingLeft, css.Keyword(string(v)))
}

// SetPaddingRight creates a declaration for the padding-right property.
func SetPaddingRight(v PaddingRightVal) css.Decl {
	return css.Set(PaddingRight, css.Keyword(string(v)))
}

// SetPaddingTop creates a declaration for the padding-top property.
func SetPaddingTop(v PaddingTopVal) css.Decl {
	return css.Set(PaddingTop, css.Keyword(string(v)))
}

// SetPage creates a declaration for the page property.
func SetPage(v PageVal) css.Decl {
	return css.Set(Page, css.Keyword(string(v)))
}

// SetPageBreakAfter creates a declaration for the page-break-after property.
func SetPageBreakAfter(v PageBreakAfterVal) css.Decl {
	return css.Set(PageBreakAfter, css.Keyword(string(v)))
}

// SetPageBreakBefore creates a declaration for the page-break-before property.
func SetPageBreakBefore(v PageBreakBeforeVal) css.Decl {
	return css.Set(PageBreakBefore, css.Keyword(string(v)))
}

// SetPageBreakInside creates a declaration for the page-break-inside property.
func SetPageBreakInside(v PageBreakInsideVal) css.Decl {
	return css.Set(PageBreakInside, css.Keyword(string(v)))
}

// SetPaintOrder creates a declaration for the paint-order property.
func SetPaintOrder(v PaintOrderVal) css.Decl {
	return css.Set(PaintOrder, css.Keyword(string(v)))
}

// SetPerspective creates a declaration for the perspective property.
func SetPerspective(v PerspectiveVal) css.Decl {
	return css.Set(Perspective, css.Keyword(string(v)))
}

// SetPerspectiveOrigin creates a declaration for the perspective-origin property.
func SetPerspectiveOrigin(v PerspectiveOriginVal) css.Decl {
	return css.Set(PerspectiveOrigin, css.Keyword(string(v)))
}

// SetPlaceContent creates a declaration for the place-content property.
func SetPlaceContent(v PlaceContentVal) css.Decl {
	return css.Set(PlaceContent, css.Keyword(string(v)))
}

// SetPlaceItems creates a declaration for the place-items property.
func SetPlaceItems(v PlaceItemsVal) css.Decl {
	return css.Set(PlaceItems, css.Keyword(string(v)))
}

// SetPlaceSelf creates a declaration for the place-self property.
func SetPlaceSelf(v PlaceSelfVal) css.Decl {
	return css.Set(PlaceSelf, css.Keyword(string(v)))
}

// SetPointerEvents creates a declaration for the pointer-events property.
func SetPointerEvents(v PointerEventsVal) css.Decl {
	return css.Set(PointerEvents, css.Keyword(string(v)))
}

// SetPosition creates a declaration for the position property.
func SetPosition(v PositionVal) css.Decl {
	return css.Set(Position, css.Keyword(string(v)))
}

// SetPrintColorAdjust creates a declaration for the print-color-adjust property.
func SetPrintColorAdjust(v PrintColorAdjustVal) css.Decl {
	return css.Set(PrintColorAdjust, css.Keyword(string(v)))
}

// SetQuotes creates a declaration for the quotes property.
func SetQuotes(v QuotesVal) css.Decl {
	return css.Set(Quotes, css.Keyword(string(v)))
}

// SetResize creates a declaration for the resize property.
func SetResize(v ResizeVal) css.Decl {
	return css.Set(Resize, css.Keyword(string(v)))
}

// SetRight creates a declaration for the right property.
func SetRight(v RightVal) css.Decl {
	return css.Set(Right, css.Keyword(string(v)))
}

// SetRotate creates a declaration for the rotate property.
func SetRotate(v RotateVal) css.Decl {
	return css.Set(Rotate, css.Keyword(string(v)))
}

// SetRowGap creates a declaration for the row-gap property.
func SetRowGap(v RowGapVal) css.Decl {
	return css.Set(RowGap, css.Keyword(string(v)))
}

// SetRubyAlign creates a declaration for the ruby-align property.
func SetRubyAlign(v RubyAlignVal) css.Decl {
	return css.Set(RubyAlign, css.Keyword(string(v)))
}

// SetRubyOverhang creates a declaration for the ruby-overhang property.
func SetRubyOverhang(v RubyOverhangVal) css.Decl {
	return css.Set(RubyOverhang, css.Keyword(string(v)))
}

// SetRubyPosition creates a declaration for the ruby-position property.
func SetRubyPosition(v RubyPositionVal) css.Decl {
	return css.Set(RubyPosition, css.Keyword(string(v)))
}

// SetScale creates a declaration for the scale property.
func SetScale(v ScaleVal) css.Decl {
	return css.Set(Scale, css.Keyword(string(v)))
}

// SetScrollBehavior creates a declaration for the scroll-behavior property.
func SetScrollBehavior(v ScrollBehaviorVal) css.Decl {
	return css.Set(ScrollBehavior, css.Keyword(string(v)))
}

// SetScrollMargin creates a declaration for the scroll-margin property.
func SetScrollMargin(v ScrollMarginVal) css.Decl {
	return css.Set(ScrollMargin, css.Keyword(string(v)))
}

// SetScrollMarginBlock creates a declaration for the scroll-margin-block property.
func SetScrollMarginBlock(v ScrollMarginBlockVal) css.Decl {
	return css.Set(ScrollMarginBlock, css.Keyword(string(v)))
}

// SetScrollMarginInline creates a declaration for the scroll-margin-inline property.
func SetScrollMarginInline(v ScrollMarginInlineVal) css.Decl {
	return css.Set(ScrollMarginInline, css.Keyword(string(v)))
}

// SetScrollPadding creates a declaration for the scroll-padding property.
func SetScrollPadding(v ScrollPaddingVal) css.Decl {
	return css.Set(ScrollPadding, css.Keyword(string(v)))
}

// SetScrollPaddingBlock creates a declaration for the scroll-padding-block property.
func SetScrollPaddingBlock(v ScrollPaddingBlockVal) css.Decl {
	return css.Set(ScrollPaddingBlock, css.Keyword(string(v)))
}

// SetScrollPaddingBlockEnd creates a declaration for the scroll-padding-block-end property.
func SetScrollPaddingBlockEnd(v ScrollPaddingBlockEndVal) css.Decl {
	return css.Set(ScrollPaddingBlockEnd, css.Keyword(string(v)))
}

// SetScrollPaddingBlockStart creates a declaration for the scroll-padding-block-start property.
func SetScrollPaddingBlockStart(v ScrollPaddingBlockStartVal) css.Decl {
	return css.Set(ScrollPaddingBlockStart, css.Keyword(string(v)))
}

// SetScrollPaddingBottom creates a declaration for the scroll-padding-bottom property.
func SetScrollPaddingBottom(v ScrollPaddingBottomVal) css.Decl {
	return css.Set(ScrollPaddingBottom, css.Keyword(string(v)))
}

// SetScrollPaddingInline creates a declaration for the scroll-padding-inline property.
func SetScrollPaddingInline(v ScrollPaddingInlineVal) css.Decl {
	return css.Set(ScrollPaddingInline, css.Keyword(string(v)))
}

// SetScrollPaddingInlineEnd creates a declaration for the scroll-padding-inline-end property.
func SetScrollPaddingInlineEnd(v ScrollPaddingInlineEndVal) css.Decl {
	return css.Set(ScrollPaddingInlineEnd, css.Keyword(string(v)))
}

// SetScrollPaddingInlineStart creates a declaration for the scroll-padding-inline-start property.
func SetScrollPaddingInlineStart(v ScrollPaddingInlineStartVal) css.Decl {
	return css.Set(ScrollPaddingInlineStart, css.Keyword(string(v)))
}

// SetScrollPaddingLeft creates a declaration for the scroll-padding-left property.
func SetScrollPaddingLeft(v ScrollPaddingLeftVal) css.Decl {
	return css.Set(ScrollPaddingLeft, css.Keyword(string(v)))
}

// SetScrollPaddingRight creates a declaration for the scroll-padding-right property.
func SetScrollPaddingRight(v ScrollPaddingRightVal) css.Decl {
	return css.Set(ScrollPaddingRight, css.Keyword(string(v)))
}

// SetScrollPaddingTop creates a declaration for the scroll-padding-top property.
func SetScrollPaddingTop(v ScrollPaddingTopVal) css.Decl {
	return css.Set(ScrollPaddingTop, css.Keyword(string(v)))
}

// SetScrollSnapAlign creates a declaration for the scroll-snap-align property.
func SetScrollSnapAlign(v ScrollSnapAlignVal) css.Decl {
	return css.Set(ScrollSnapAlign, css.Keyword(string(v)))
}

// SetScrollSnapCoordinate creates a declaration for the scroll-snap-coordinate property.
func SetScrollSnapCoordinate(v ScrollSnapCoordinateVal) css.Decl {
	return css.Set(ScrollSnapCoordinate, css.Keyword(string(v)))
}

// SetScrollSnapDestination creates a declaration for the scroll-snap-destination property.
func SetScrollSnapDestination(v ScrollSnapDestinationVal) css.Decl {
	return css.Set(ScrollSnapDestination, css.Keyword(string(v)))
}

// SetScrollSnapPointsX creates a declaration for the scroll-snap-points-x property.
func SetScrollSnapPointsX(v ScrollSnapPointsXVal) css.Decl {
	return css.Set(ScrollSnapPointsX, css.Keyword(string(v)))
}

// SetScrollSnapPointsY creates a declaration for the scroll-snap-points-y property.
func SetScrollSnapPointsY(v ScrollSnapPointsYVal) css.Decl {
	return css.Set(ScrollSnapPointsY, css.Keyword(string(v)))
}

// SetScrollSnapStop creates a declaration for the scroll-snap-stop property.
func SetScrollSnapStop(v ScrollSnapStopVal) css.Decl {
	return css.Set(ScrollSnapStop, css.Keyword(string(v)))
}

// SetScrollSnapType creates a declaration for the scroll-snap-type property.
func SetScrollSnapType(v ScrollSnapTypeVal) css.Decl {
	return css.Set(ScrollSnapType, css.Keyword(string(v)))
}

// SetScrollSnapTypeX creates a declaration for the scroll-snap-type-x property.
func SetScrollSnapTypeX(v ScrollSnapTypeXVal) css.Decl {
	return css.Set(ScrollSnapTypeX, css.Keyword(string(v)))
}

// SetScrollSnapTypeY creates a declaration for the scroll-snap-type-y property.
func SetScrollSnapTypeY(v ScrollSnapTypeYVal) css.Decl {
	return css.Set(ScrollSnapTypeY, css.Keyword(string(v)))
}

// SetScrollbarColor creates a declaration for the scrollbar-color property.
func SetScrollbarColor(v ScrollbarColorVal) css.Decl {
	return css.Set(ScrollbarColor, css.Keyword(string(v)))
}

// SetScrollbarGutter creates a declaration for the scrollbar-gutter property.
func SetScrollbarGutter(v ScrollbarGutterVal) css.Decl {
	return css.Set(ScrollbarGutter, css.Keyword(string(v)))
}

// SetScrollbarWidth creates a declaration for the scrollbar-width property.
func SetScrollbarWidth(v ScrollbarWidthVal) css.Decl {
	return css.Set(ScrollbarWidth, css.Keyword(string(v)))
}

// SetShapeOutside creates a declaration for the shape-outside property.
func SetShapeOutside(v ShapeOutsideVal) css.Decl {
	return css.Set(ShapeOutside, css.Keyword(string(v)))
}

// SetShapeRendering creates a declaration for the shape-rendering property.
func SetShapeRendering(v ShapeRenderingVal) css.Decl {
	return css.Set(ShapeRendering, css.Keyword(string(v)))
}

// SetStopOpacity creates a declaration for the stop-opacity property.
func SetStopOpacity(v StopOpacityVal) css.Decl {
	return css.Set(StopOpacity, css.Keyword(string(v)))
}

// SetStroke creates a declaration for the stroke property.
func SetStroke(v StrokeVal) css.Decl {
	return css.Set(Stroke, css.Keyword(string(v)))
}

// SetStrokeDasharray creates a declaration for the stroke-dasharray property.
func SetStrokeDasharray(v StrokeDasharrayVal) css.Decl {
	return css.Set(StrokeDasharray, css.Keyword(string(v)))
}

// SetStrokeLinecap creates a declaration for the stroke-linecap property.
func SetStrokeLinecap(v StrokeLinecapVal) css.Decl {
	return css.Set(StrokeLinecap, css.Keyword(string(v)))
}

// SetStrokeLinejoin creates a declaration for the stroke-linejoin property.
func SetStrokeLinejoin(v StrokeLinejoinVal) css.Decl {
	return css.Set(StrokeLinejoin, css.Keyword(string(v)))
}

// SetStrokeOpacity creates a declaration for the stroke-opacity property.
func SetStrokeOpacity(v StrokeOpacityVal) css.Decl {
	return css.Set(StrokeOpacity, css.Keyword(string(v)))
}

// SetTabSize creates a declaration for the tab-size property.
func SetTabSize(v TabSizeVal) css.Decl {
	return css.Set(TabSize, css.Keyword(string(v)))
}

// SetTableLayout creates a declaration for the table-layout property.
func SetTableLayout(v TableLayoutVal) css.Decl {
	return css.Set(TableLayout, css.Keyword(string(v)))
}

// SetTextAlign creates a declaration for the text-align property.
func SetTextAlign(v TextAlignVal) css.Decl {
	return css.Set(TextAlign, css.Keyword(string(v)))
}

// SetTextAlignLast creates a declaration for the text-align-last property.
func SetTextAlignLast(v TextAlignLastVal) css.Decl {
	return css.Set(TextAlignLast, css.Keyword(string(v)))
}

// SetTextAnchor creates a declaration for the text-anchor property.
func SetTextAnchor(v TextAnchorVal) css.Decl {
	return css.Set(TextAnchor, css.Keyword(string(v)))
}

// SetTextAutospace creates a declaration for the text-autospace property.
func SetTextAutospace(v TextAutospaceVal) css.Decl {
	return css.Set(TextAutospace, css.Keyword(string(v)))
}

// SetTextBox creates a declaration for the text-box property.
func SetTextBox(v TextBoxVal) css.Decl {
	return css.Set(TextBox, css.Keyword(string(v)))
}

// SetTextBoxEdge creates a declaration for the text-box-edge property.
func SetTextBoxEdge(v TextBoxEdgeVal) css.Decl {
	return css.Set(TextBoxEdge, css.Keyword(string(v)))
}

// SetTextBoxTrim creates a declaration for the text-box-trim property.
func SetTextBoxTrim(v TextBoxTrimVal) css.Decl {
	return css.Set(TextBoxTrim, css.Keyword(string(v)))
}

// SetTextCombineUpright creates a declaration for the text-combine-upright property.
func SetTextCombineUpright(v TextCombineUprightVal) css.Decl {
	return css.Set(TextCombineUpright, css.Keyword(string(v)))
}

// SetTextDecoration creates a declaration for the text-decoration property.
func SetTextDecoration(v TextDecorationVal) css.Decl {
	return css.Set(TextDecoration, css.Keyword(string(v)))
}

// SetTextDecorationColor creates a declaration for the text-decoration-color property.
func SetTextDecorationColor(v TextDecorationColorVal) css.Decl {
	return css.Set(TextDecorationColor, css.Keyword(string(v)))
}

// SetTextDecorationLine creates a declaration for the text-decoration-line property.
func SetTextDecorationLine(v TextDecorationLineVal) css.Decl {
	return css.Set(TextDecorationLine, css.Keyword(string(v)))
}

// SetTextDecorationSkipInk creates a declaration for the text-decoration-skip-ink property.
func SetTextDecorationSkipInk(v TextDecorationSkipInkVal) css.Decl {
	return css.Set(TextDecorationSkipInk, css.Keyword(string(v)))
}

// SetTextDecorationStyle creates a declaration for the text-decoration-style property.
func SetTextDecorationStyle(v TextDecorationStyleVal) css.Decl {
	return css.Set(TextDecorationStyle, css.Keyword(string(v)))
}

// SetTextDecorationThickness creates a declaration for the text-decoration-thickness property.
func SetTextDecorationThickness(v TextDecorationThicknessVal) css.Decl {
	return css.Set(TextDecorationThickness, css.Keyword(string(v)))
}

// SetTextEmphasis creates a declaration for the text-emphasis property.
func SetTextEmphasis(v TextEmphasisVal) css.Decl {
	return css.Set(TextEmphasis, css.Keyword(string(v)))
}

// SetTextEmphasisColor creates a declaration for the text-emphasis-color property.
func SetTextEmphasisColor(v TextEmphasisColorVal) css.Decl {
	return css.Set(TextEmphasisColor, css.Keyword(string(v)))
}

// SetTextEmphasisPosition creates a declaration for the text-emphasis-position property.
func SetTextEmphasisPosition(v TextEmphasisPositionVal) css.Decl {
	return css.Set(TextEmphasisPosition, css.Keyword(string(v)))
}

// SetTextEmphasisStyle creates a declaration for the text-emphasis-style property.
func SetTextEmphasisStyle(v TextEmphasisStyleVal) css.Decl {
	return css.Set(TextEmphasisStyle, css.Keyword(string(v)))
}

// SetTextIndent creates a declaration for the text-indent property.
func SetTextIndent(v TextIndentVal) css.Decl {
	return css.Set(TextIndent, css.Keyword(string(v)))
}

// SetTextJustify creates a declaration for the text-justify property.
func SetTextJustify(v TextJustifyVal) css.Decl {
	return css.Set(TextJustify, css.Keyword(string(v)))
}

// SetTextOrientation creates a declaration for the text-orientation property.
func SetTextOrientation(v TextOrientationVal) css.Decl {
	return css.Set(TextOrientation, css.Keyword(string(v)))
}

// SetTextOverflow creates a declaration for the text-overflow property.
func SetTextOverflow(v TextOverflowVal) css.Decl {
	return css.Set(TextOverflow, css.Keyword(string(v)))
}

// SetTextRendering creates a declaration for the text-rendering property.
func SetTextRendering(v TextRenderingVal) css.Decl {
	return css.Set(TextRendering, css.Keyword(string(v)))
}

// SetTextShadow creates a declaration for the text-shadow property.
func SetTextShadow(v TextShadowVal) css.Decl {
	return css.Set(TextShadow, css.Keyword(string(v)))
}

// SetTextTransform creates a declaration for the text-transform property.
func SetTextTransform(v TextTransformVal) css.Decl {
	return css.Set(TextTransform, css.Keyword(string(v)))
}

// SetTextUnderlineOffset creates a declaration for the text-underline-offset property.
func SetTextUnderlineOffset(v TextUnderlineOffsetVal) css.Decl {
	return css.Set(TextUnderlineOffset, css.Keyword(string(v)))
}

// SetTextUnderlinePosition creates a declaration for the text-underline-position property.
func SetTextUnderlinePosition(v TextUnderlinePositionVal) css.Decl {
	return css.Set(TextUnderlinePosition, css.Keyword(string(v)))
}

// SetTextWrap creates a declaration for the text-wrap property.
func SetTextWrap(v TextWrapVal) css.Decl {
	return css.Set(TextWrap, css.Keyword(string(v)))
}

// SetTextWrapMode creates a declaration for the text-wrap-mode property.
func SetTextWrapMode(v TextWrapModeVal) css.Decl {
	return css.Set(TextWrapMode, css.Keyword(string(v)))
}

// SetTextWrapStyle creates a declaration for the text-wrap-style property.
func SetTextWrapStyle(v TextWrapStyleVal) css.Decl {
	return css.Set(TextWrapStyle, css.Keyword(string(v)))
}

// SetTop creates a declaration for the top property.
func SetTop(v TopVal) css.Decl {
	return css.Set(Top, css.Keyword(string(v)))
}

// SetTouchAction creates a declaration for the touch-action property.
func SetTouchAction(v TouchActionVal) css.Decl {
	return css.Set(TouchAction, css.Keyword(string(v)))
}

// SetTransform creates a declaration for the transform property.
func SetTransform(v TransformVal) css.Decl {
	return css.Set(Transform, css.Keyword(string(v)))
}

// SetTransformBox creates a declaration for the transform-box property.
func SetTransformBox(v TransformBoxVal) css.Decl {
	return css.Set(TransformBox, css.Keyword(string(v)))
}

// SetTransformOrigin creates a declaration for the transform-origin property.
func SetTransformOrigin(v TransformOriginVal) css.Decl {
	return css.Set(TransformOrigin, css.Keyword(string(v)))
}

// SetTransformStyle creates a declaration for the transform-style property.
func SetTransformStyle(v TransformStyleVal) css.Decl {
	return css.Set(TransformStyle, css.Keyword(string(v)))
}

// SetTransition creates a declaration for the transition property.
func SetTransition(v TransitionVal) css.Decl {
	return css.Set(Transition, css.Keyword(string(v)))
}

// SetTransitionBehavior creates a declaration for the transition-behavior property.
func SetTransitionBehavior(v TransitionBehaviorVal) css.Decl {
	return css.Set(TransitionBehavior, css.Keyword(string(v)))
}

// SetTransitionDelay creates a declaration for the transition-delay property.
func SetTransitionDelay(v TransitionDelayVal) css.Decl {
	return css.Set(TransitionDelay, css.Keyword(string(v)))
}

// SetTransitionDuration creates a declaration for the transition-duration property.
func SetTransitionDuration(v TransitionDurationVal) css.Decl {
	return css.Set(TransitionDuration, css.Keyword(string(v)))
}

// SetTransitionProperty creates a declaration for the transition-property property.
func SetTransitionProperty(v TransitionPropertyVal) css.Decl {
	return css.Set(TransitionProperty, css.Keyword(string(v)))
}

// SetTransitionTimingFunction creates a declaration for the transition-timing-function property.
func SetTransitionTimingFunction(v TransitionTimingFunctionVal) css.Decl {
	return css.Set(TransitionTimingFunction, css.Keyword(string(v)))
}

// SetTranslate creates a declaration for the translate property.
func SetTranslate(v TranslateVal) css.Decl {
	return css.Set(Translate, css.Keyword(string(v)))
}

// SetUnicodeBidi creates a declaration for the unicode-bidi property.
func SetUnicodeBidi(v UnicodeBidiVal) css.Decl {
	return css.Set(UnicodeBidi, css.Keyword(string(v)))
}

// SetUserSelect creates a declaration for the user-select property.
func SetUserSelect(v UserSelectVal) css.Decl {
	return css.Set(UserSelect, css.Keyword(string(v)))
}

// SetVectorEffect creates a declaration for the vector-effect property.
func SetVectorEffect(v VectorEffectVal) css.Decl {
	return css.Set(VectorEffect, css.Keyword(string(v)))
}

// SetVerticalAlign creates a declaration for the vertical-align property.
func SetVerticalAlign(v VerticalAlignVal) css.Decl {
	return css.Set(VerticalAlign, css.Keyword(string(v)))
}

// SetViewTransitionClass creates a declaration for the view-transition-class property.
func SetViewTransitionClass(v ViewTransitionClassVal) css.Decl {
	return css.Set(ViewTransitionClass, css.Keyword(string(v)))
}

// SetViewTransitionName creates a declaration for the view-transition-name property.
func SetViewTransitionName(v ViewTransitionNameVal) css.Decl {
	return css.Set(ViewTransitionName, css.Keyword(string(v)))
}

// SetVisibility creates a declaration for the visibility property.
func SetVisibility(v VisibilityVal) css.Decl {
	return css.Set(Visibility, css.Keyword(string(v)))
}

// SetWhiteSpace creates a declaration for the white-space property.
func SetWhiteSpace(v WhiteSpaceVal) css.Decl {
	return css.Set(WhiteSpace, css.Keyword(string(v)))
}

// SetWhiteSpaceCollapse creates a declaration for the white-space-collapse property.
func SetWhiteSpaceCollapse(v WhiteSpaceCollapseVal) css.Decl {
	return css.Set(WhiteSpaceCollapse, css.Keyword(string(v)))
}

// SetWidows creates a declaration for the widows property.
func SetWidows(v WidowsVal) css.Decl {
	return css.Set(Widows, css.Keyword(string(v)))
}

// SetWidth creates a declaration for the width property.
func SetWidth(v WidthVal) css.Decl {
	return css.Set(Width, css.Keyword(string(v)))
}

// SetWillChange creates a declaration for the will-change property.
func SetWillChange(v WillChangeVal) css.Decl {
	return css.Set(WillChange, css.Keyword(string(v)))
}

// SetWordBreak creates a declaration for the word-break property.
func SetWordBreak(v WordBreakVal) css.Decl {
	return css.Set(WordBreak, css.Keyword(string(v)))
}

// SetWordSpacing creates a declaration for the word-spacing property.
func SetWordSpacing(v WordSpacingVal) css.Decl {
	return css.Set(WordSpacing, css.Keyword(string(v)))
}

// SetWordWrap creates a declaration for the word-wrap property.
func SetWordWrap(v WordWrapVal) css.Decl {
	return css.Set(WordWrap, css.Keyword(string(v)))
}

// SetWritingMode creates a declaration for the writing-mode property.
func SetWritingMode(v WritingModeVal) css.Decl {
	return css.Set(WritingMode, css.Keyword(string(v)))
}

// SetZIndex creates a declaration for the z-index property.
func SetZIndex(v ZIndexVal) css.Decl {
	return css.Set(ZIndex, css.Keyword(string(v)))
}

// SetZoom creates a declaration for the zoom property.
func SetZoom(v ZoomVal) css.Decl {
	return css.Set(Zoom, css.Keyword(string(v)))
}
